In [1]:
import jax.numpy as jnp

In [2]:
jnp.array([0, 1, 0])

Array([0, 1, 0], dtype=int32)

In [10]:
b1 = jnp.array(list(range(0, 8192))[::-1])
b1

Array([8191, 8190, 8189, ...,    2,    1,    0], dtype=int32)

In [11]:
b2 = jnp.array(range(8192, 77909120))

In [9]:
b2

Array([81920, 81921, 81922, ..., 90109, 90110, 90111], dtype=int32)

In [12]:
indices = jnp.concatenate([b1, b2])

In [13]:
indices

Array([    8191,     8190,     8189, ..., 77909117, 77909118, 77909119],      dtype=int32)

In [14]:
jnp.save('test_perm.npy', indices)